export const ProjectsData = [
  {
    id: 1,
    title: "Project 1",
    client: "PN",
    tasks: 8,
    languages: 2,
    application: "Word",
    pages: 150,
    dueDate: "2025-07-06",
    qcDeadline: "2025-07-04",
    qcHours: 12,
    qcDueDate: "2025-07-05",
    status: "Near Due",
    handler: "Alice",
    processStatus: "Completed",
    qaReviewer: "Lisa",
    qaStatus: "Passed",
    serverPath: "/mnt/server/project/project-1",
    taskTypes: ["OVA", "Image Localization", "Source Creation"],
    applications: ["PPT", "Word", "AI"],
    languagesList: ["sv", "de"],
  },
  {
    id: 2,
    title: "Project 2",
    client: "MMP Auburn",
    tasks: 8,
    languages: 3,
    application: "FM",
    pages: 150,
    dueDate: "2025-07-01",
    qcDeadline: "2025-06-29",
    qcHours: 10,
    qcDueDate: "2025-06-30",
    status: "Active",
    handler: "John",
    processStatus: "Completed",
    qaReviewer: "Lisa",
    qaStatus: "Passed",
    serverPath: "/mnt/server/project/project-2",
    taskTypes: ["Source Creation", "DTP"],
    applications: ["Project", "Word", "CDR"],
    languagesList: ["es-ES", "hi", "ne"],
  },
  {
    id: 3,
    title: "Project 3",
    client: "MMP Eastlake",
    tasks: 4,
    languages: 4,
    application: "Project",
    pages: 150,
    dueDate: "2025-07-13",
    qcDeadline: "2025-07-11",
    qcHours: 7,
    qcDueDate: "2025-07-12",
    status: "Active",
    handler: "Bob",
    processStatus: "Pending",
    qaReviewer: "Lisa",
    qaStatus: "In Review",
    serverPath: "/mnt/server/project/project-3",
    taskTypes: ["Source Creation"],
    applications: ["PSD"],
    languagesList: ["he", "mr", "es-MX", "bg"],
  },
  {
    id: 4,
    title: "Project 4",
    client: "MMP Kirkland",
    tasks: 3,
    languages: 1,
    application: "Visio",
    pages: 120,
    dueDate: "2025-07-13",
    qcDeadline: "2025-07-11",
    qcHours: 5,
    qcDueDate: "2025-07-12",
    status: "Near Due",
    handler: "Eve",
    processStatus: "Ongoing",
    qaReviewer: "Mike",
    qaStatus: "In Review",
    serverPath: "/mnt/server/project/project-4",
    taskTypes: ["Prep", "Image Localization", "DTP"],
    applications: ["CDR", "PPT"],
    languagesList: ["be"],
  },
  {
    id: 5,
    title: "Project 5",
    client: "GN",
    tasks: 3,
    languages: 4,
    application: "CDR",
    pages: 180,
    dueDate: "2025-07-07",
    qcDeadline: "2025-07-05",
    qcHours: 5,
    qcDueDate: "2025-07-06",
    status: "Active",
    handler: "Bob",
    processStatus: "Completed",
    qaReviewer: "Mike",
    qaStatus: "Pending",
    serverPath: "/mnt/server/project/project-5",
    taskTypes: ["Image Localization", "Prep"],
    applications: ["PSD", "INDD", "PPT"],
    languagesList: ["bs", "zh-TW", "sr-Cyrl", "zh"],
  },
  {
    id: 6,
    title: "Project 6",
    client: "DM",
    tasks: 3,
    languages: 4,
    application: "AE",
    pages: 150,
    dueDate: "2025-07-10",
    qcDeadline: "2025-07-08",
    qcHours: 5,
    qcDueDate: "2025-07-09",
    status: "Active",
    handler: "Bob",
    processStatus: "Ongoing",
    qaReviewer: "Alan",
    qaStatus: "Failed",
    serverPath: "/mnt/server/project/project-6",
    taskTypes: ["Source Creation", "OVA", "Callout"],
    applications: ["CDR", "Word", "AI"],
    languagesList: ["pa", "mn", "mt", "lt"],
  },
  {
    id: 7,
    title: "Project 7",
    client: "RN",
    tasks: 3,
    languages: 1,
    application: "PSD",
    pages: 60,
    dueDate: "2025-07-02",
    qcDeadline: "2025-06-30",
    qcHours: 14,
    qcDueDate: "2025-07-01",
    status: "Near Due",
    handler: "John",
    processStatus: "Ongoing",
    qaReviewer: "Mike",
    qaStatus: "Passed",
    serverPath: "/mnt/server/project/project-7",
    taskTypes: ["Image Creation"],
    applications: ["PPT", "Word"],
    languagesList: ["so"],
  },
  {
    id: 8,
    title: "Project 8",
    client: "NI",
    tasks: 4,
    languages: 5,
    application: "AI",
    pages: 90,
    dueDate: "2025-06-30",
    qcDeadline: "2025-06-28",
    qcHours: 12,
    qcDueDate: "2025-06-29",
    status: "Active",
    handler: "Charlie",
    processStatus: "Ongoing",
    qaReviewer: "Alan",
    qaStatus: "Failed",
    serverPath: "/mnt/server/project/project-8",
    taskTypes: ["Prep"],
    applications: ["INDD", "Excel"],
    languagesList: ["es-MX", "vi", "fil", "km", "am"],
  },
  {
    id: 9,
    title: "Project 9",
    client: "LB",
    tasks: 8,
    languages: 5,
    application: "INDD",
    pages: 150,
    dueDate: "2025-07-08",
    qcDeadline: "2025-07-06",
    qcHours: 14,
    qcDueDate: "2025-07-07",
    status: "Near Due",
    handler: "David",
    processStatus: "Pending",
    qaReviewer: "Mike",
    qaStatus: "In Review",
    serverPath: "/mnt/server/project/project-9",
    taskTypes: ["Callout", "DTP"],
    applications: ["Project", "FM", "Word"],
    languagesList: ["he", "km", "ku", "zh-Hant", "en"],
  },
  {
    id: 10,
    title: "Project 10",
    client: "SSS",
    tasks: 8,
    languages: 2,
    application: "Excel",
    pages: 120,
    dueDate: "2025-07-03",
    qcDeadline: "2025-07-01",
    qcHours: 7,
    qcDueDate: "2025-07-02",
    status: "Near Due",
    handler: "Bob",
    processStatus: "Completed",
    qaReviewer: "Sarah",
    qaStatus: "Failed",
    serverPath: "/mnt/server/project/project-10",
    taskTypes: ["DTP"],
    applications: ["AI", "Excel"],
    languagesList: ["af", "el"],
  },
  {
    id: 11,
    title: "Project 11",
    client: "Cpea",
    tasks: 6,
    languages: 5,
    application: "PPT",
    pages: 60,
    dueDate: "2025-06-30",
    qcDeadline: "2025-06-28",
    qcHours: 14,
    qcDueDate: "2025-06-29",
    status: "Overdue",
    handler: "Alice",
    processStatus: "Delayed",
    qaReviewer: "Lisa",
    qaStatus: "In Review",
    serverPath: "/mnt/server/project/project-11",
    taskTypes: ["Image Creation"],
    applications: ["INDD", "Visio"],
    languagesList: ["mn", "zh", "nl", "ar", "te"],
  },
  {
    id: 12,
    title: "Project 12",
    client: "CV",
    tasks: 7,
    languages: 5,
    application: "Word",
    pages: 180,
    dueDate: "2025-07-02",
    qcDeadline: "2025-06-30",
    qcHours: 10,
    qcDueDate: "2025-07-01",
    status: "Near Due",
    handler: "Bob",
    processStatus: "Completed",
    qaReviewer: "Lisa",
    qaStatus: "In Review",
    serverPath: "/mnt/server/project/project-12",
    taskTypes: ["DTP", "Source Creation", "OVA"],
    applications: ["Project", "PSD", "INDD"],
    languagesList: ["sr-Latn", "bs", "vi", "mt", "gl"],
  },
];